# Generated by Django 6.0.1 on 2026-01-18 05:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryAlbum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('contest', '웅변대회'), ('memorial', '추모행사'), ('education', '교육활동'), ('global', '국제교류'), ('meeting', '회의/행사')], max_length=20, verbose_name='카테고리')),
                ('title', models.CharField(max_length=200, verbose_name='앨범명')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('event_date', models.DateField(verbose_name='행사일')),
                ('cover_image', models.ImageField(blank=True, upload_to='gallery/covers/%Y/', verbose_name='대표이미지')),
                ('is_featured', models.BooleanField(default=False, verbose_name='최신앨범표시')),
                ('views', models.IntegerField(default=0, verbose_name='조회수')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '갤러리 앨범',
                'verbose_name_plural': '갤러리 앨범 관리',
                'ordering': ['-event_date'],
            },
        ),
        migrations.CreateModel(
            name='GalleryVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('youtube_url', models.URLField(verbose_name='YouTube 링크')),
                ('thumbnail', models.ImageField(blank=True, upload_to='gallery/videos/', verbose_name='썸네일')),
                ('duration', models.CharField(max_length=10, verbose_name='재생시간')),
                ('views', models.IntegerField(default=0, verbose_name='조회수')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '영상',
                'verbose_name_plural': '영상 갤러리 관리',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=50, verbose_name='언론사')),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('excerpt', models.TextField(verbose_name='요약')),
                ('link_url', models.URLField(verbose_name='원문링크')),
                ('thumbnail', models.ImageField(blank=True, upload_to='news/thumbnails/%Y/%m/', verbose_name='썸네일')),
                ('is_featured', models.BooleanField(default=False, verbose_name='주요보도')),
                ('published_date', models.DateField(verbose_name='보도일')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '보도자료',
                'verbose_name_plural': '보도자료 관리',
                'ordering': ['-published_date'],
            },
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('important', '중요'), ('event', '행사'), ('contest', '웅변대회'), ('general', '일반')], max_length=20, verbose_name='카테고리')),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('content', models.TextField(verbose_name='내용')),
                ('author', models.CharField(max_length=50, verbose_name='작성부서')),
                ('views', models.IntegerField(default=0, verbose_name='조회수')),
                ('is_pinned', models.BooleanField(default=False, verbose_name='상단고정')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '공지사항',
                'verbose_name_plural': '공지사항 관리',
                'ordering': ['-is_pinned', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery/images/%Y/%m/')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='설명')),
                ('order', models.IntegerField(default=0, verbose_name='정렬순서')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='archive.galleryalbum')),
            ],
            options={
                'verbose_name': '갤러리 이미지',
                'verbose_name_plural': '갤러리 이미지',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
