# Generated by Django 6.0.1 on 2026-01-18 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Popup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='제목')),
                ('pc_image', models.ImageField(upload_to='popup/', verbose_name='PC 이미지')),
                ('mobile_image', models.ImageField(upload_to='popup/', verbose_name='모바일 이미지')),
                ('link_url', models.URLField(blank=True, verbose_name='클릭시 이동URL')),
                ('start_at', models.DateTimeField(verbose_name='노출 시작일시')),
                ('end_at', models.DateTimeField(verbose_name='노출 종료일시')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '팝업',
                'verbose_name_plural': '팝업 관리',
                'ordering': ['-created_at'],
            },
        ),
    ]
