# Generated by Django 6.0.1 on 2026-01-18 05:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VolunteerApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='이름')),
                ('birth_date', models.DateField(verbose_name='생년월일')),
                ('phone', models.CharField(max_length=11, verbose_name='연락처')),
                ('email', models.EmailField(max_length=254, verbose_name='이메일')),
                ('occupation', models.CharField(max_length=100, verbose_name='직업/소속')),
                ('programs', models.JSONField(verbose_name='참여 프로그램')),
                ('available_dates', models.TextField(verbose_name='참여 가능 일정')),
                ('experience', models.TextField(blank=True, verbose_name='관련 경험')),
                ('motivation', models.TextField(verbose_name='지원 동기')),
                ('privacy_agreed', models.BooleanField(default=False, verbose_name='개인정보동의')),
                ('is_confirmed', models.BooleanField(default=False, verbose_name='승인여부')),
                ('admin_memo', models.TextField(blank=True, verbose_name='관리자메모')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '자원봉사 신청',
                'verbose_name_plural': '자원봉사 신청 관리',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donation_type', models.CharField(choices=[('once', '일시 후원'), ('monthly', '정기 후원')], max_length=10, verbose_name='후원유형')),
                ('amount', models.IntegerField(verbose_name='후원금액')),
                ('donor_name', models.CharField(max_length=50, verbose_name='후원자명')),
                ('phone', models.CharField(max_length=11, verbose_name='연락처')),
                ('email', models.EmailField(max_length=254, verbose_name='이메일')),
                ('receipt_requested', models.BooleanField(default=False, verbose_name='영수증요청')),
                ('receipt_name', models.CharField(blank=True, max_length=50, verbose_name='영수증 발급명')),
                ('receipt_id', models.CharField(blank=True, max_length=20, verbose_name='주민/사업자번호')),
                ('is_confirmed', models.BooleanField(default=False, verbose_name='입금확인')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='입금확인일시')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='회원')),
            ],
            options={
                'verbose_name': '후원',
                'verbose_name_plural': '후원 관리',
                'ordering': ['-created_at'],
            },
        ),
    ]
