# Generated by Django 6.0.1 on 2026-01-26 08:43

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board_type', models.CharField(choices=[('notice', '공지사항'), ('news', '보도자료'), ('gallery', '갤러리'), ('video', '영상'), ('member_notice', '회원 공지'), ('member_resource', '회원 자료실')], max_length=30, unique=True, verbose_name='게시판')),
                ('read_permission', models.CharField(choices=[('ALL', '전체 공개'), ('FREE', '무료회원 이상'), ('SUPPORTER', '후원회원 전용'), ('ADMIN', '관리자 전용')], default='ALL', max_length=20, verbose_name='읽기 권한')),
                ('write_permission', models.CharField(choices=[('ALL', '전체 공개'), ('FREE', '무료회원 이상'), ('SUPPORTER', '후원회원 전용'), ('ADMIN', '관리자 전용')], default='ADMIN', max_length=20, verbose_name='쓰기 권한')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화')),
            ],
            options={
                'verbose_name': '게시판 권한',
                'verbose_name_plural': '게시판 권한 설정',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('tier', models.CharField(choices=[('FREE', '무료회원'), ('SUPPORTER', '후원회원')], default='FREE', max_length=10, verbose_name='회원등급')),
                ('tier_approved_at', models.DateTimeField(blank=True, null=True, verbose_name='후원회원 승인일')),
                ('admin_level', models.CharField(choices=[('NONE', '일반회원'), ('STAFF', '운영진'), ('SUPER', '최고관리자')], default='NONE', max_length=10, verbose_name='관리자등급')),
                ('phone', models.CharField(max_length=11, verbose_name='연락처')),
                ('address', models.TextField(blank=True, verbose_name='주소')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='생년월일')),
                ('occupation', models.CharField(blank=True, max_length=100, verbose_name='직업/소속')),
                ('join_source', models.CharField(blank=True, choices=[('search', '인터넷 검색'), ('sns', 'SNS'), ('recommend', '지인 추천'), ('event', '행사 참여'), ('news', '언론 보도'), ('other', '기타')], max_length=20, verbose_name='가입경로')),
                ('join_message', models.TextField(blank=True, verbose_name='가입동기')),
                ('marketing_agreed', models.BooleanField(default=False, verbose_name='마케팅수신동의')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('tier_approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_users', to=settings.AUTH_USER_MODEL, verbose_name='승인 관리자')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '회원',
                'verbose_name_plural': '회원 관리',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
