# Generated by Django 6.0.1 on 2026-01-18 05:45

import django.contrib.auth.models
import django.contrib.auth.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('tier', models.CharField(choices=[('FREE', '무료회원'), ('L1', '일반회원'), ('L2', '후원회원'), ('L3', '평생회원'), ('SPECIAL', '특별회원')], default='FREE', max_length=10, verbose_name='회원등급')),
                ('tier_expires_at', models.DateField(blank=True, null=True, verbose_name='등급만료일')),
                ('email_verified', models.BooleanField(default=False, verbose_name='이메일인증')),
                ('nickname', models.CharField(blank=True, max_length=50, verbose_name='활동명')),
                ('phone', models.CharField(max_length=11, verbose_name='연락처')),
                ('address', models.TextField(blank=True, verbose_name='주소')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='생년월일')),
                ('occupation', models.CharField(blank=True, max_length=100, verbose_name='직업/소속')),
                ('join_source', models.CharField(blank=True, choices=[('search', '인터넷 검색'), ('sns', 'SNS'), ('recommend', '지인 추천'), ('event', '행사 참여'), ('news', '언론 보도'), ('other', '기타')], max_length=20, verbose_name='가입경로')),
                ('join_message', models.TextField(blank=True, verbose_name='가입동기')),
                ('is_donor', models.BooleanField(default=False, verbose_name='CMS후원여부')),
                ('marketing_agreed', models.BooleanField(default=False, verbose_name='마케팅수신동의')),
                ('social_provider', models.CharField(blank=True, choices=[('', '일반'), ('kakao', '카카오'), ('naver', '네이버'), ('google', '구글')], max_length=20, verbose_name='소셜로그인')),
                ('social_id', models.CharField(blank=True, max_length=100, verbose_name='소셜ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '회원',
                'verbose_name_plural': '회원 관리',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
